// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7GOx6KuK023fSr-Mo0imyoukurLIwavA',
    appId: '1:902658213411:web:4e1ef72aea1c0120449396',
    messagingSenderId: '902658213411',
    projectId: 'bestiary-eb19d',
    authDomain: 'bestiary-eb19d.firebaseapp.com',
    storageBucket: 'bestiary-eb19d.appspot.com',
    measurementId: 'G-M6D9B6P5MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkgariAN3tQu_VbyRDKl3p0JFVTaUheb4',
    appId: '1:902658213411:android:99aa1f15f33333ec449396',
    messagingSenderId: '902658213411',
    projectId: 'bestiary-eb19d',
    storageBucket: 'bestiary-eb19d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjV0Z1jmD9Npfr6HT72EOFmKBKRwmoLc8',
    appId: '1:902658213411:ios:b293b0d50983216d449396',
    messagingSenderId: '902658213411',
    projectId: 'bestiary-eb19d',
    storageBucket: 'bestiary-eb19d.appspot.com',
    iosBundleId: 'com.example.animalCollectables',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjV0Z1jmD9Npfr6HT72EOFmKBKRwmoLc8',
    appId: '1:902658213411:ios:1abf0d78f436ed38449396',
    messagingSenderId: '902658213411',
    projectId: 'bestiary-eb19d',
    storageBucket: 'bestiary-eb19d.appspot.com',
    iosBundleId: 'com.example.animalCollectables.RunnerTests',
  );
}
